Areas/Admin/Controllers/MapCourseSubjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sipl.DataBase;

namespace Sipl.Areas.Admin.Controllers
{
    [Authorize]
    public class MapCourseSubjectController : Controller
    {
        private SiplDatabaseEntities db = new SiplDatabaseEntities();
        /// <summary>
        /// list of Course in Subject
        /// </summary>
        /// <returns></returns>
        public ActionResult GetMapCourseSubject()
        {
            //query for list
            var subjectInCourse = db.SubjectInCourse.Include(s => s.Courses).Include(s => s.Subjects);
            return View(subjectInCourse.ToList());
        }

        /// <summary>
        /// Get Method For Maping Course In Subject method
        /// </summary>
        /// <returns></returns>
        public ActionResult CreateSubjectInCourse()
        {
            //for getting Course
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName");
            //for getting Subject
            ViewBag.SubjectId = new SelectList(db.Subjects, "SubjectId", "SubjectName");
            return View();
        }

       
        /// <summary>
        /// post method for mapping
        /// </summary>
        /// <param name="subjectInCourse"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSubjectInCourse([Bind(Include = "Id,SubjectId,CourseId")] SubjectInCourse subjectInCourse)
        {
            if (ModelState.IsValid)
            {
                db.SubjectInCourse.Add(subjectInCourse);
                db.SaveChanges();
                return RedirectToAction("GetMapCourseSubject");
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", subjectInCourse.CourseId);
            ViewBag.SubjectId = new SelectList(db.Subjects, "SubjectId", "SubjectName", subjectInCourse.SubjectId);
            return View(subjectInCourse);
        }

   
        /// <summary>
        /// Update method for mapping  
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult EditSubjectInCourse(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubjectInCourse subjectInCourse = db.SubjectInCourse.Find(id);
            if (subjectInCourse == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", subjectInCourse.CourseId);
            ViewBag.SubjectId = new SelectList(db.Subjects, "SubjectId", "SubjectName", subjectInCourse.SubjectId);
            return View(subjectInCourse);
        }

        /// <summary>
        /// post method for Update
        /// </summary>
        /// <param name="subjectInCourse"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult EditSubjectInCourse([Bind(Include = "Id,SubjectId,CourseId")] SubjectInCourse subjectInCourse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subjectInCourse).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("GetMapCourseSubject");
            }
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "CourseName", subjectInCourse.CourseId);
            ViewBag.SubjectId = new SelectList(db.Subjects, "SubjectId", "SubjectName", subjectInCourse.SubjectId);

            return View(subjectInCourse);
        }

       /// <summary>
       /// Get method for delete 
       /// </summary>
       /// <param name="id"></param>
       /// <returns></returns>
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SubjectInCourse subjectInCourse = db.SubjectInCourse.Find(id);
            if (subjectInCourse == null)
            {
                return HttpNotFound();
            }
            return View(subjectInCourse);
        }

        /// <summary>
        /// delete post method 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SubjectInCourse subjectInCourse = db.SubjectInCourse.Find(id);
            db.SubjectInCourse.Remove(subjectInCourse);
            db.SaveChanges();
            return RedirectToAction("GetMapCourseSubject");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/MapCourseSubject/CreateSubjectInCourse.cshtml
@model Sipl.DataBase.SubjectInCourse

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Map Subjects in Courses</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "SubjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", null, "--Select Subject---", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, "----Select Course----", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>

    <a type="button" class="btn btn-primary btn-sm"
       href="@Url.Action("GetMapCourseSubject", "MapCourseSubject")">
        <span class="glyphicon glyphicon-list"></span>
        <span>Back to list</span>
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Admin/Views/MapCourseSubject/Delete.cshtml
@model Sipl.DataBase.SubjectInCourse


<h4>DeleteConfirmed</h4>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SubjectInCourse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Courses.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Courses.CourseName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subjects.SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subjects.SubjectName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a type="button" class="btn btn-primary btn-sm"
           href="@Url.Action("GetMapCourseSubject", "MapCourseSubject")">
            <span class="glyphicon glyphicon-list"></span>
            <span>Back to list</span>
        </a>
    </div>
    }
</div>

Areas/Admin/Views/MapCourseSubject/EditSubjectInCourse.cshtml
@model Sipl.DataBase.SubjectInCourse

<h4>Update list</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Subjects, "SubjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Courses, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-success" />
            </div>
        </div>
    </div>
}

    <div>

        <a type="button" class="btn btn-primary btn-sm"
           href="@Url.Action("GetMapCourseSubject", "MapCourseSubject")">
            <span class="glyphicon glyphicon-list"></span>
            <span>Back to list</span>
        </a>
    </div>

Areas/Admin/Views/MapCourseSubject/GetMapCourseSubject.cshtml
@model IEnumerable<Sipl.DataBase.SubjectInCourse>

@{
    ViewBag.Title = "List of Subjects in Courses";
}

<h2>Index</h2>

<p>
<p>
    <a type="button" class="btn btn-primary btn-sm"
       href="@Url.Action("Index", "Home", new { area = "" })">
        <span class="glyphicon glyphicon-list"></span>
        <span>Back to Main menu</span>
    </a>
    <a type="button" class="btn btn-primary btn-sm"
       href="@Url.Action("CreateSubjectInCourse")">
        <span class="glyphicon glyphicon-plus"></span>
        <span>Map New</span>
    </a>
</p>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Courses.CourseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subjects.SubjectName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Courses.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subjects.SubjectName)
            </td>
            <td>
                @Html.ActionLink( "Edit", "EditSubjectInCourse", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>