Areas/Admin/Controllers/TeacherInfoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using Sipl.App_Start;
using Sipl.Areas.Admin.Models;
using Sipl.DataBase;
using Sipl.Models;

namespace Sipl.Areas.Admin.Controllers
{
    [Authorize]
    public class TeacherInfoController : Controller
    {
        SiplDatabaseEntities objEntities = new SiplDatabaseEntities();
        // GET: Admin/TeacherInfo
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult _TeacherGridPartial()
        {

            return View();
        }

        /// <summary>
        /// GET data from db
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult UserSearchView()
        {
            try
            {
                //TO GET ROLES FROM DATABASE
                var roles = (from b in objEntities.NetRoles select b).ToList();
                var model = new FilterViewModel();

                model.Role = roles.Select(x => new SelectListItem
                {
                    Value = x.RoleId,
                    Text = x.RoleName
                }).ToList();

                //GET : COURSE FOR USERS
                var course = (from b in objEntities.Courses select b).ToList();
                model.Course = course.Select(x => new SelectListItem
                {
                    Value = x.CourseId.ToString(),
                    Text = x.CourseName
                });

                //TO GET COUNTRY ,STATES AND CITY
                var country = objEntities.Countries.ToList();
                List<SelectListItem> listCountry = new List<SelectListItem>();
                List<SelectListItem> listState = new List<SelectListItem>();
                List<SelectListItem> listCity = new List<SelectListItem>();

                listCountry.Add(new SelectListItem { Text = "", Value = "0" });
                listState.Add(new SelectListItem { Text = "", Value = "0" });
                listCity.Add(new SelectListItem { Text = "", Value = "0" });

                foreach (var m in country)
                {
                    listCountry.Add(new SelectListItem { Text = m.CountryName, Value = m.CountryId.ToString() });
                }
                ViewBag.country = listCountry;
                ViewBag.State = listState;
                ViewBag.City = listCity;

                List<SearchViewModel> objSearchViewModel = new List<SearchViewModel>();

                //Get List of users from DB
                var data = (from p in objEntities.NetUsers select p).ToList();
                foreach (var item in data)
                {
                    //To get Address From DB
                    var userAddressInfo = (from p in objEntities.Address
                                           where p.UserId == item.UserId
                                           select p).FirstOrDefault();

                    var getCourse = (from c in objEntities.Courses
                                     where c.CourseId == item.CourseId
                                     select c).FirstOrDefault();

                    var getRole = (from role in objEntities.NetRoles
                                   join user in objEntities.UserRole
                                   on role.RoleId equals user.RoleId
                                   where user.UserId == item.UserId
                                   select role.RoleName).FirstOrDefault();


                    if (userAddressInfo != null)

                    {
                        SearchViewModel searchView = new SearchViewModel
                        {
                            UserId = item.UserId,
                            FirstName = item.FirstName,
                            LastName = item.LastName,
                            Gender = item.Gender,
                            Email = item.Email,
                            CourseId = item.CourseId,
                            RoleName = getRole,
                            DOB = item.DOB,
                            IsVerified = item.IsVerified,
                            IsActive = item.IsActive,


                            CurrentAddress = userAddressInfo.CurrentAddress,
                            PermanantAddress = userAddressInfo.PermanantAddress,
                            Country = userAddressInfo.Countries.CountryName,
                            States = userAddressInfo.States.StateName,
                            Cities = userAddressInfo.Cities.CityName,
                            Pincode = userAddressInfo.Pincode,
                            DateCreated = item.DateCreated
                        };
                        objSearchViewModel.Add(searchView);
                    }
                    model.List = objSearchViewModel;
                };


                return View(model);
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="objFilterViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserSearchView(FilterViewModel objFilterViewModel)
        {

            //TO GET ROLES FROM DATABASE
            var roles = (from b in objEntities.NetRoles select b).ToList();
            var model = new FilterViewModel
            {
                Role = roles.Select(x => new SelectListItem
                {
                    Value = x.RoleId,
                    Text = x.RoleName
                }).ToList()
            };

            //GET : COURSE FOR USERS
            var course = (from b in objEntities.Courses select b).ToList();
            model.Course = course.Select(x => new SelectListItem
            {
                Value = x.CourseId.ToString(),
                Text = x.CourseName
            });

            //TO GET COUNTRY ,STATES AND CITY
            var country = objEntities.Countries.ToList();
            List<SelectListItem> listCountry = new List<SelectListItem>();
            List<SelectListItem> listState = new List<SelectListItem>();
            List<SelectListItem> listCity = new List<SelectListItem>();

            listCountry.Add(new SelectListItem { Text = "", Value = "0" });
            listState.Add(new SelectListItem { Text = "", Value = "0" });
            listCity.Add(new SelectListItem { Text = "", Value = "0" });

            foreach (var m in country)
            {
                listCountry.Add(new SelectListItem { Text = m.CountryName, Value = m.CountryId.ToString() });
            }
            ViewBag.country = listCountry;
            ViewBag.State = listState;
            ViewBag.City = listCity;



            //to compare filters' data in database.
            var searchBar = (from
                                  user in objEntities.NetUsers
                             join userRole in objEntities.UserRole on user.UserId equals userRole.UserId
                             join Address in objEntities.Address on user.UserId equals Address.UserId



                             where user.Courses.CourseId == objFilterViewModel.CourseId || objFilterViewModel.CourseId == null

                             where userRole.RoleId == objFilterViewModel.RoleId || string.IsNullOrEmpty(objFilterViewModel.RoleId)

                             select new SearchViewModel
                             {
                                 UserId = user.UserId,
                                 FirstName = user.FirstName,
                                 LastName = user.LastName,
                                 Gender = user.Gender,
                                 DOB = user.DOB,
                                 Email = user.Email,
                                 //IsEmailVerified = user.IsEmailVerified,
                                 IsActive = user.IsActive,
                                 CourseName = user.Courses.CourseName,
                                 CurrentAddress = Address.CurrentAddress,
                                 PermanantAddress = Address.PermanantAddress,
                                 Country = Address.Countries.CountryName,
                                 States = Address.States.StateName,
                                 Cities = Address.Cities.CityName,
                                 //Pincode = user.Address.Pincode,
                                 DateCreated = user.DateCreated,
                                 //DateModified = user.DateModified,
                                 RoleName = userRole.NetRoles.RoleName
                             }).ToList();

            model.List = searchBar;
            //return PartialView(model);
            return View(model);
        }

        /// <summary>
        /// Assin Subject
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult SubjectAssign(int id)
        {

            var subject = (from b in objEntities.Subjects select b).ToList();
            var model = new FilterViewModel
            {
                SubjectAssign = subject.Select(x => new SelectListItem
                {
                    Value = x.SubjectId.ToString(),
                    Text = x.SubjectName
                }).ToList()
            };

            var getUser = (from d in objEntities.Address
                           join c in objEntities.NetUsers on d.UserId equals c.UserId
                           join s in objEntities.UserRole on c.UserId equals s.UserId
                           where d.UserId == id
                           select new FilterViewModel
                           {
                               UserId = c.UserId,

Areas/Admin/Views/TeacherInfo/SubjectAssign.cshtml
@model Sipl.Areas.Admin.Models.FilterViewModel
@{

    ViewBag.Title = "Assign Subject";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.HiddenFor(model => model.UserId)
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SubjectAssign, "Subject", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">       
                @Html.DropDownListFor(model => model.SubjectId, Model.SubjectAssign, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectAssign, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Assign Subject" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    <a type="button" class="btn btn-primary btn-sm"
       href="@Url.Action("UserSearchView","TeacherInfo")">
        <span class="glyphicon glyphicon-list"></span>
        <span>Back to List</span>
    </a>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Admin/Views/TeacherInfo/TeacherInSubjectlist.cshtml
@model IEnumerable<Sipl.Areas.Admin.Models.FilterViewModel>
@{
    ViewBag.Title = "TeacherInSubjectlist";
}
<h2>TeacherInSubjectlist</h2>
<p>
    <a type="button" class="btn btn-primary btn-sm"
       href="@Url.Action("UserSearchView","TeacherInfo")">
        <span class="glyphicon glyphicon-list"></span>
        <span>Back to List</span>
    </a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubjectAssign)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subjects)
            </td>
        </tr>
    }
</table>

Areas/Admin/Views/TeacherInfo/TeacherProfile.cshtml
@model Sipl.Models.NetUserViewModel
@{
    ViewBag.Title = "LoggedIn";
}

<fieldset>
    <legend>
        <text>
            @if (Session["Email"] != null)
            {
                <text>
                    Welcome!!!!! @Session["Email"].ToString()
                </text>
            }
        </text>
    </legend>
</fieldset>
<h2>Hello!! Sir</h2>
<div>
    <ul>
        <li>
    @Html.RouteLink("View Student ", "Default",
          new { action = "_TeacherPage", controller = "Admin/TeacherInfo", id = Model.UserId })
            </li>
        <li>

    @Html.RouteLink("View Profile ", "Default",
         new { action = "TeacherDetails", controller = "NetUserView", id = Model.UserId })
            </li>
        </ul>
</div>

Areas/Admin/Views/TeacherInfo/UserProfile.cshtml
@model Sipl.Models.NetUserViewModel
@{
    ViewBag.Title = "LoggedIn";
}

<fieldset>
    <legend>
        <text>
            @if (Session["Email"] != null)
            {
                <text>
                    Welcome!!!!! @Session["Email"].ToString()
                </text>
            }
        </text>
    </legend>
</fieldset>

@if (Convert.ToInt32(Session["RoleId"]) == 2)
{
    <h2>Hello!! Buddy</h2>
    <div>
        <ul>
            <li>
                @Html.RouteLink("View Teacher ", "Default",
              new { action = "_StudentPage", controller = "Admin/TeacherInfo" , id = Model.UserId })
            </li>
            <li>
                @Html.RouteLink("View Profile ", "Default",
                         new { action = "RegisteredUserDetails", controller = "NetUserView", id = Model.UserId })
            </li>
        </ul>
    </div>
}
else if (Convert.ToInt32(Session["RoleId"]) == 1)
{
    <h2>Hello!! Sir</h2>

    <div>
        @Html.RouteLink("View Student ", "Default",
             new { action = "_TeacherPage", controller = "Admin/TeacherInfo" })
    </div>
    <div>
        @Html.RouteLink("Edit Profile ", "Default",
            new { action = "RegisteredUserDetails", controller = "NetUserView", id = Model.UserId })
    </div>


}

Areas/Admin/Views/TeacherInfo/UserSearchView.cshtml
@model Sipl.Areas.Admin.Models.FilterViewModel
@{
    ViewBag.Title = "UserSearchView";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div>
        <div>
            <a type="button" class="btn btn-primary btn-sm"
               href="@Url.Action("Index", "Home", new { area = "" })">
                <span class="glyphicon glyphicon-list"></span>
                <span>Back to Main Menu</span>
            </a>
            <hr>
            <h2>Search User based on their Roles</h2>
            <br>
            <hr>
        </div>
        <div class="form-horizontal">
            <div class="col-md-12">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.DropDownListFor(model => model.RoleId, Model.Role, "Select", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Course, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.CourseId, Model.Course, "--select--", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" align="center" class="btn btn-success" />
        </div>
    </div>
}
<div>
    @Html.Partial("_TeacherGridPartial", Model)
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Admin/Views/TeacherInfo/_StudentPage.cshtml
@model IEnumerable<Sipl.Models.NetUserViewModel>

@{
    ViewBag.Title = "_StudentPage";
}

<h2>List of Student</h2>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.SubjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.CourseName)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.SubjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>

        </tr>
    }


</table>
<div>
    @*<a type="button" class="btn btn-primary btn-sm"
           href="@Url.Action("UserProfile","TeacherInfo")">
            <span class="glyphicon glyphicon-home"></span>
            <span>Back to Main Menu</span>
        </a>
        @Html.RouteLink("Back to Main Menu ", "Default",
                    new { action = "UserProfile", controller = "TeacherInfo",id = ViewBag.UserId  })*@
    <a type="button" class="btn btn-primary btn" href="@Url.Action("UserProfile","TeacherInfo",new { id =  ViewBag.UserId})"

    <span>Back To HomePage</span>
</a>


</div>

Areas/Admin/Views/TeacherInfo/_TeacherGridPartial.cshtml
@model Sipl.Areas.Admin.Models.FilterViewModel
@{
    ViewBag.Title = "_TeacherGridPartial";
}
<hr>
<h2>List of Users</h2>
<hr>
<table class="table table-striped table ">
    <tr class="success">
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Role)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrentAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PermanantAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.States)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cities)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pincode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsVerified)
        </th>
    </tr>
    @foreach (var item in Model.List)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrentAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PermanantAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.States)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cities)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pincode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsVerified)
            </td>

            <td>
                @Html.RouteLink("Edit", "Default",
            new { action = "UpdateRegisteredUsers", controller = "NetUserView", id = item.UserId  })
                |
                @Html.RouteLink("Delete", "Default",
          new { action = "DeleteRegisteredUsers", controller = "NetUserView", id = item.UserId  })
                |


                @if (item.RoleName == "Teacher")

                {
                    @Html.ActionLink("SubjectAssign", "SubjectAssign", new { id = item.UserId })
                    <span>|</span>
                    @Html.ActionLink("TeacherInSubjectlist", "TeacherInSubjectlist", new { id = item.UserId })
                }
            </td>


        </tr>
    }
</table>

Areas/Admin/Views/TeacherInfo/_TeacherPage.cshtml
@model IEnumerable<Sipl.Models.NetUserViewModel>
<h2>List of Students</h2>
<div>
    <a type="button" class="btn btn-primary btn-sm"
        href="@Url.Action("TeacherProfile","TeacherInfo", new { Id= ViewBag.SendId })">
         <span class="glyphicon glyphicon-list"></span>
         <span>Back to Main Menu</span>

    </a>
    @*@Html.RouteLink("Back to Menu ", "Default",
new { action = "TeacherProfile", controller = "Admin/TeacherInfo", id = Model.UserId })*@

</div>

<table class="table table-striped table ">
    <tr class="success">
        <th>
            @Html.DisplayName("UserId")
        </th>
        <th>
            @Html.DisplayName("FirstName")
        </th>
        <th>
            @Html.DisplayName("LastName")
        </th>
        <th>
            @Html.DisplayName("Course")
        </th>
       
        <th>
            @Html.DisplayName("DOB")
        </th>
        
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.CourseName)
        </td>
       <td>
            @Html.DisplayFor(modelItem => item.DOB)
        </td>
       
        <td>
            @Html.RouteLink("ViewProfile", "Default",
                    new { action = "RegisteredUserDetails", controller = "NetUserView", id = item.UserId  })
        </td>

    </tr>
    }
</table>