Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sipl.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}

Controllers/NetUserViewController.cs
using Sipl.App_Start;
using Sipl.DataBase;
using Sipl.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Routing;

namespace Sipl.Controllers
{
    public class NetUserViewController : Controller
    {
        SiplDatabaseEntities objEntities = new SiplDatabaseEntities();
        /// <summary>
        /// List of all Registered User 
        /// </summary>
        /// <returns></returns>
        public ActionResult RegisteredUserList()
        {
            // Get user roles from DB
            ViewBag.Role = new SelectList(objEntities.NetRoles.ToList(), "RoleId", "RoleName");
            List<NetUserViewModel> objNetUserViewModel = new List<NetUserViewModel>();

            //Get List of users from DB
            var data = (from p in objEntities.NetUsers select p).ToList();
            foreach (var item in data)
            {
                //To get Address From DB
                var userAddressInfo = (from p in objEntities.Address where p.UserId == item.UserId select p).FirstOrDefault();
                if (userAddressInfo != null)
                {
                    NetUserViewModel netUser = new NetUserViewModel
                    {
                        UserId = item.UserId,
                        FirstName = item.FirstName,
                        LastName = item.LastName,
                        Gender = item.Gender,
                        Email = item.Email,
                        Password = item.Password,
                        DOB = item.DOB,
                        IsActive = item.IsActive,
                        CurrentAddress = userAddressInfo.CurrentAddress,
                        PermanantAddress = userAddressInfo.PermanantAddress,
                        Country = userAddressInfo.Countries.CountryName,
                        States = userAddressInfo.States.StateName,
                        Cities = userAddressInfo.Cities.CityName,
                        DateCreated = item.DateCreated
                    };
                    objNetUserViewModel.Add(netUser);
                }
            };
            return View(objNetUserViewModel);
        }

        /// <summary>
        /// Details of Registered Users
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult RegisteredUserDetails(int? id)
        {
            NetUserViewModel objNetUserViewModel = new NetUserViewModel();
            try
            {
                ViewBag.SendId = id;

                var getUser = (from d in objEntities.Address
                               join c in objEntities.NetUsers on d.UserId equals c.UserId
                               join s in objEntities.UserRole on c.UserId equals s.UserId
                               join e in objEntities.SubjectInCourse on c.CourseId equals e.CourseId
                               where d.UserId == id

                               select new NetUserViewModel
                               {
                                   UserId = c.UserId,
                                   FirstName = c.FirstName,
                                   LastName = c.LastName,
                                   Password = c.Password,
                                   RoleId = s.RoleId,
                                   Gender = c.Gender,
                                   DOB = c.DOB,
                                   Email = c.Email,
                                   IsVerified = c.IsVerified,
                                   IsActive = c.IsActive,
                                   DateCreated = c.DateCreated,
                                   CourseName = c.Courses.CourseName,
                                   CurrentAddress = d.CurrentAddress,
                                   PermanantAddress = d.PermanantAddress,
                                   Country = d.Countries.CountryName,
                                   States = d.States.StateName,
                                   Cities = d.Cities.CityName,
                                   Pincode = d.Pincode
                               }).FirstOrDefault();
                return View(getUser);
            }
            catch (Exception er)
            {
                Console.Write(er.Message);
                return View();
            }
        }
        public ActionResult TeacherDetails(int? id)
        {
            NetUserViewModel objNetUserViewModel = new NetUserViewModel();
            try
            {

                var getUser = (from d in objEntities.Address
                               join c in objEntities.NetUsers on d.UserId equals c.UserId
                               join s in objEntities.UserRole on c.UserId equals s.UserId
                               join f in objEntities.TeacherInSubject on c.UserId equals f.UserId
                               join su in objEntities.Subjects on f.SubjectId equals su.SubjectId
                               where d.UserId == id

                               select new NetUserViewModel
                               {
                                   UserId = c.UserId,
                                   FirstName = c.FirstName,
                                   LastName = c.LastName,
                                   Password = c.Password,
                                   RoleId = s.RoleId,
                                   Gender = c.Gender,
                                   DOB = c.DOB,
                                   Email = c.Email,
                                   IsVerified = c.IsVerified,
                                   IsActive = c.IsActive,
                                   DateCreated = c.DateCreated,
                                   SubjectName = su.SubjectName,
                                   CurrentAddress = d.CurrentAddress,
                                   PermanantAddress = d.PermanantAddress,
                                   Country = d.Countries.CountryName,
                                   States = d.States.StateName,
                                   Cities = d.Cities.CityName,
                                   Pincode = d.Pincode
                               }).FirstOrDefault();
                return View(getUser);
            }
            catch (Exception er)
            {
                Console.Write(er.Message);
                return View();
            }
        }

        /// <summary>
        ///GET :Registration Method For Users
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult RegisterUser()
        {
            //TO GET ROLES FROM DATABASE
            var roles = (from b in objEntities.NetRoles select b).ToList();
            var model = new NetUserViewModel
            {
                Role = roles.Select(x => new SelectListItem
                {
                    Value = x.RoleId,
                    Text = x.RoleName
                }).ToList()
            };
            //GET : COURSE FOR USERS
            var course = (from b in objEntities.Courses select b).ToList();
            model.Course = course.Select(x => new SelectListItem
            {
                Value = x.CourseId.ToString(),
                Text = x.CourseName
            });
            //TO GET COUNTRY ,STATES AND CITY
            {
                var country = objEntities.Countries.ToList();
                List<SelectListItem> listCountry = new List<SelectListItem>();
                List<SelectListItem> listState = new List<SelectListItem>();
                List<SelectListItem> listCity = new List<SelectListItem>();


                foreach (var m in country)
                {
                    listCountry.Add(new SelectListItem { Text = m.CountryName, Value = m.CountryId.ToString() });
                }
                ViewBag.country = listCountry;
                ViewBag.State = listState;
                ViewBag.City = listCity;
            }
            return View(model);
        }

        /// <summary>
        /// Post: Register Method For Users
        /// </summary>
        /// <param name="objNetUserViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisterUser(NetUserViewModel objNetUserViewModel)
        {
            using (var dbTransaction = objEntities.Database.BeginTransaction())
            {
                ViewBag.Role = new SelectList(objEntities.NetRoles.ToList(), "RoleId", "RoleName");
                try
                {
                    if (ModelState.IsValid)
                    {
                        //Encrytion For Password
                        var keyNew = "Test";
                        var password = Helper.EncodePassword(objNetUserViewModel.Password, keyNew);

                        NetUsers objNetUsers = new NetUsers
                        {
                            FirstName = objNetUserViewModel.FirstName,
                            LastName = objNetUserViewModel.LastName,
                            Gender = objNetUserViewModel.Gender,
                            CourseId = objNetUserViewModel.CourseId,
                            Email = objNetUserViewModel.Email,
                            Password = password,
                            DOB = objNetUserViewModel.DOB,
                            IsActive = objNetUserViewModel.IsActive,
                            DateCreated = DateTime.Now,
                            DateModified = DateTime.Now,
                        };
                        objEntities.NetUsers.Add(objNetUsers);
                        objEntities.SaveChanges();
                        //to get userId
                        var userId = objNetUsers.UserId;

                        // to specify UserRole according to their UserI
                        UserRole objUserRole = new UserRole

Views/Login/LogIn.cshtml
@model Sipl.Models.LoginViewModel

<style>


    .table-bordered {
       
        width: 960px;
        color: navy;
        border: 2px solid darkblue;
        padding: 5px;
    }
    }
</style>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="table-bordered">
        <div class="form-horizontal">
            <h3>Please Login....</h3>
            <br>
            <br>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group ">
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="checkbox">
                        @Html.CheckBoxFor(m => m.RememberMe)
                        @Html.LabelFor(m => m.RememberMe)
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create New Account" class="btn btn-success"
                           onclick="window.location.href='@Url.Action("RegisterUser", "NetUserView")'" />
                    <span>|</span>
                    <input type="submit" value="Log in " class="btn btn-success" />

                </div>
            </div>
        </div>
      </div> 
}
@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Login/LoggedIn.cshtml
@{
    ViewBag.Title = "LoggedIn";
}
<h2>Holla!! Admin</h2>
<fieldset>
    <legend>
        <text>
            @if (Session["Email"] != null)
            {
                <text>
                    Welcome!!!!! @Session["Email"].ToString()
                </text>
            }
        </text>
    </legend>
</fieldset>

Views/Login/RegisteredUser.cshtml
@{
    ViewBag.Title = "Registered User";
}
<h2>   Thankyou For Registration !!!</h2>
<div>
    @if (Session["FirstName"] != null)
    {
        <text>
            Thankyou For Registration !!!  @Session["FirstName"].ToString()
        </text>
    }
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <a type="button" class="btn btn-primary btn-sm"
           href="@Url.Action("Index", "Home", new { area = "" })">
            <span class="glyphicon glyphicon-home"></span>
            <span>Back to Main Menu</span>
        </a>
        <input type="submit" value=" LogIn To Continue" class="btn btn-success"
               onclick="window.location.href='@Url.Action("LogIn", "LogIn")'" />
    </div>
</div>

Views/Login/_AdminPage.cshtml
@model IEnumerable<Sipl.Models.NetUserViewModel>
<h2>Index</h2>

<table class="table table-striped table ">
    <tr class="success">
        <th>
            @Html.DisplayName("FirstName")
        </th>
        <th>
            @Html.DisplayName("LastName")
        </th>
        <th>
            @Html.DisplayName("Role")
        </th>
        <th>
            @Html.DisplayName("Course")
        </th>
        <th>
            @Html.DisplayName("Gender")
        </th>
        <th>
            @Html.DisplayName("Email")
        </th>
        <th>
            @Html.DisplayName("IsActive")
        </th>
        <th>
            @Html.DisplayName("IsVerified")
        </th>
        
        <th>
            @Html.DisplayName("CurrentAddress")
        </th>
        <th>
            @Html.DisplayName("PermanantAddress")
        </th>
        <th>
            @Html.DisplayName("Country")
        </th>
        <th>
            @Html.DisplayName("States")
        </th>
        <th>
            @Html.DisplayName("Cities")
        </th>
        <th>
            @Html.DisplayName("Pincode")
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoleId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsVerified)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrentAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PermanantAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.States)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cities)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pincode)
            </td>

        </tr>
    }
</table>

Views/Login/ttest.cshtml
@model StudentProject.Models.MapCourseAndSubjectViewModel
@{
    ViewBag.Title = "Add Course";
}
<div>
    <h2>Add Course</h2>
    <div class="w3-container w3-teal">
        @using (Html.BeginForm("MapCourseAndSubject", "SuperAdmin", FormMethod.Post))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.CourseList, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.CourseList, Model.CourseList.Select(item => new SelectListItem
               {
                   Value = item.CourseId.ToString(),
                   Text = item.CourseName.ToString()

               }), "---Select Course---", new { id = "ddlCourse" })
                    @Html.ValidationMessageFor(model => model.CourseList, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.SubjectList, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.SubjectList, Model.SubjectList.Select(item => new SelectListItem
               {
                   Value = item.SubjectId.ToString(),
                   Text = item.SubjectName.ToString()

               }), "---Select Course---", new { id = "ddlCourse" })
                    @Html.ValidationMessageFor(model => model.SubjectList, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="MapCourseAndSubject" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
</div>