Areas/Admin/Models/CourseViewModel.cs
using Sipl.DataBase;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sipl.Areas.Admin.Models
{
    public class CourseViewModel
    {
        public int CourseId { get; set; }

        [Required]
        public string CourseName { get; set; }
    }
}

Areas/Admin/Controllers/CourseController.cs
using Sipl.Areas.Admin.Models;
using Sipl.DataBase;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Sipl.Areas.Admin.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        SiplDatabaseEntities objEntities = new SiplDatabaseEntities();
        /// <summary>
        ///  List of all Courses Added by Admin
        /// </summary>
        /// <returns></returns>
        public ActionResult GetCourse()
        {
            List<CourseViewModel> objCourseViewModel = new List<CourseViewModel>();
            var data = (from p in objEntities.Courses select p).ToList();
            foreach (var item in data)
            {
                CourseViewModel course = new CourseViewModel
                {
                    CourseId = item.CourseId,
                    CourseName = item.CourseName
                  
                };
                objCourseViewModel.Add(course);
            };
            return View(objCourseViewModel);
        }
        /// <summary>
        /// GET: Create Method For Course
        /// </summary>
        /// <returns></returns>
        public ActionResult CreateCourse(string id)
        {
           return View();
        }
        /// <summary>
        /// POST :Create Method For Course
        /// </summary>
        /// <param name="objCourseViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCourse(CourseViewModel objCourseViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Courses objCourses = new Courses
                    {
                        CourseName = objCourseViewModel.CourseName,
                     
                    };
                    var test = objEntities.Courses.Add(objCourses);
                    objEntities.SaveChanges();
                    
                };
                return RedirectToAction("GetCourse", "Course", objCourseViewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        /// <summary>
        /// get method for update 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult EditCourse(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = objEntities.Courses.Find(id);
            var data = from d in objEntities.Courses
                       where d.CourseId == id
                       select d;
            //var TEMPlIST = objEntities.Subjects.ToList();
            CourseViewModel courseView = new CourseViewModel
            {
                CourseId = Convert.ToInt32(courses.CourseId),
                CourseName = courses.CourseName
            
            };
            if (courses == null)
            {
                return HttpNotFound();
            }
          
            return View(courseView);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="objCourses"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult EditCourse(int id, Courses objCourses)

        {
            {
                if (ModelState.IsValid)

                {
                    Courses objCourse = new Courses
                    {
                        CourseId = id,
                        CourseName = objCourses.CourseName
                       



                    };
                    objEntities.Entry(objCourse).State = EntityState.Modified;
                    objEntities.SaveChanges();
                    return RedirectToAction("GetCourse");
                }
                return View(objCourses);
            }

        }
        /// <summary>
        /// Delete method for only courses
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeleteCourse(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = objEntities.Courses.Find(id);
            var data = from d in objEntities.Courses
                       where d.CourseId == id
                       select d;
            //var TEMPlIST = objEntities.Subjects.ToList();
            CourseViewModel courseView = new CourseViewModel
            {
                CourseId = Convert.ToInt32(courses.CourseId),
                CourseName = courses.CourseName
            };
            if (courses == null)
            {
                return HttpNotFound();
            }
            return View(courseView);
        }
        /// <summary>
        /// method for deletting course
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteCourse(int id)

        {
            try
            {
                Courses courses = objEntities.Courses.Find(id);
                objEntities.Courses.Remove(courses);
                objEntities.SaveChanges();
                return RedirectToAction("GetCourse");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception source: delete failed", ex.Message);
                return View(ex);
            }
        }
        /// <summary>
        /// logout
        /// </summary>
        /// <returns></returns>




    }
}

Areas/Admin/Controllers/SubjectController.cs
using Sipl.Areas.Admin.Models;
using Sipl.DataBase;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Sipl.Areas.Admin.Controllers
{
    [Authorize]
    public class SubjectController : Controller
    {
        SiplDatabaseEntities objEntities = new SiplDatabaseEntities();
        /// <summary>
        ///  List of all Subjects
        /// </summary>
        /// <returns></returns>
        public ActionResult GetSubject()
        {
            List<SubjectViewModel> objSubjectViewModel = new List<SubjectViewModel>();
            var data = (from p in objEntities.Subjects select p).ToList();
            foreach (var item in data)
            {
                SubjectViewModel subject = new SubjectViewModel
                {
                    SubjectId = item.SubjectId,
                    SubjectName = item.SubjectName,
                    
                };
                objSubjectViewModel.Add(subject);
            };
            return View(objSubjectViewModel);
        }

        /// <summary>
        ///  GET :Admin/Subject/To Create Subject
        /// </summary>
        /// <returns></returns>
        public ActionResult CreateSubject()
        {
            return View();
        }

        /// <summary>
        /// POST : Admin/Subject/To Create Subject
        /// </summary>
        /// <param name="objSubjectViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSubject(SubjectViewModel objSubjectViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Subjects objSubjects = new Subjects
                    {
                        SubjectName = objSubjectViewModel.SubjectName
                    };
                    objEntities.Subjects.Add(objSubjects);
                    objEntities.SaveChanges();
                    return RedirectToAction("GetSubject");
                };
                return View(objSubjectViewModel);
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// GET :Admin/Subject/Edit
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult EditSubject(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subjects subjects = objEntities.Subjects.Find(id);
            var data = from d in objEntities.Subjects
                       where d.SubjectId == id
                       select d;
            //var TEMPlIST = objEntities.Subjects.ToList();
            SubjectViewModel subjectView = new SubjectViewModel
            {
                SubjectId = subjects.SubjectId,
                SubjectName = subjects.SubjectName
            };
            if (subjects == null)
            {
                return HttpNotFound();
            }
            return View(subjectView);
        }

        /// <summary>
        ///  POST :Admin/Subject/Edit
        /// </summary>
        /// <param name="id"></param>
        /// <param name="collection"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult EditSubject(int id, Subjects objSubjects)

        {
            {
                if (ModelState.IsValid)

                {
                    Subjects objSubject = new Subjects
                    {
                        SubjectId = id,
                        SubjectName = objSubjects.SubjectName

                    };
                    objEntities.Entry(objSubject).State = EntityState.Modified;
                    objEntities.SaveChanges();
                    return RedirectToAction("GetSubject");
                }
                return View(objSubjects);
            }

        }
        /// <summary>
        /// Admin/Subject/Delete
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeleteSubject(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subjects subjects = objEntities.Subjects.Find(id);
            var data = from d in objEntities.Subjects
                       where d.SubjectId == id
                       select d;
            //var TEMPlIST = objEntities.Subjects.ToList();
            SubjectViewModel subjectView = new SubjectViewModel
            {
                SubjectId = subjects.SubjectId,
                SubjectName = subjects.SubjectName
            };
            if (subjects == null)
            {
                return HttpNotFound();
            }
            return View(subjectView);
        }

        /// <summary>
        /// Admin/Subject/Delete
        /// </summary>
        /// <param name="id"></param>
        /// <param name="collection"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteSubject(int id, SubjectViewModel objSubjectViewModel)
     
        {
            try
            {
               


                Subjects subjects = objEntities.Subjects.Find(id);
                objEntities.Subjects.Remove(subjects);
                objEntities.SaveChanges();
             

                return RedirectToAction("GetSubject");
            }
            catch (Exception ex)
            {
             Console.WriteLine("Exception source: {0} user is failed to register", ex.Message);
                return View(ex);
            }

        }
   
    }
}

Areas/Admin/Views/Course/CreateCourse.cshtml
@model Sipl.Areas.Admin.Models.CourseViewModel
@{

    ViewBag.Title = "Create";
}
<h2>Create New Course</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Courses</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
            </div>
        </div>
      
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    <a type="button" class="btn btn-primary btn-sm"
       href="@Url.Action("GetSubject","Subject")">
        <span class="glyphicon glyphicon-list"></span>
        <span>Back to List</span>
    </a>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Admin/Views/Course/DeleteCourse.cshtml
}@model Sipl.Areas.Admin.Models.CourseViewModel
@{
    ViewBag.Title = "DeleteCourse";

}
<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseName)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a type="button" class="btn btn-primary btn-sm"
               href="@Url.Action("GetCourse","Course")">
                <span class="glyphicon glyphicon-list"></span>
                <span>Back to List</span>
            </a>
        </div>
    }
</div>

Areas/Admin/Views/Course/EditCourse.cshtml
@model Sipl.Areas.Admin.Models.CourseViewModel
@{
    ViewBag.Title = "EditCourse";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
            </div>
        </div>
    
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    <a type="button" class="btn btn-primary btn-sm"
       href="@Url.Action("GetSubject","Subject")">
        <span class="glyphicon glyphicon-list"></span>
        <span>Back to List</span>
    </a>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Admin/Views/Course/GetCourse.cshtml
@model IEnumerable<Sipl.Areas.Admin.Models.CourseViewModel>
@{
    ViewBag.Title = "Index";
}
<h2>List of Courses</h2>
<p>
    <a type="button" class="btn btn-primary btn-sm"
       href="@Url.Action("Index", "Home", new { area = "" })">
        <span class="glyphicon glyphicon-list"></span>
        <span>Back to Main menu</span>
    </a>
    <a type="button" class="btn btn-primary btn-sm"
       href="@Url.Action("CreateCourse")">
        <span class="glyphicon glyphicon-plus"></span>
        <span>Create New</span>
    </a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CourseName)
        </th>
       
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CourseName)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "EditCourse", new { id = item.CourseId }) |
            @Html.ActionLink("Delete", "DeleteCourse", new { id = item.CourseId })
        </td>
    </tr>
    }
</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Admin/Views/Course/Index.cshtml
@model IEnumerable<Sipl.Areas.Admin.Models.CourseViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CourseName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CourseId }) |
                @Html.ActionLink("Details", "Details", new { id = item.CourseId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CourseId })
            </td>
        </tr>
    }

</table>